### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tmcDepix** [lsl001006/ZONE#1]
Hello!
This is an awesome work!!

I would love to get it running here and possibly make some modifications. Is it possible to add a license for it?
(the default license means one can only read the code and anything else)
[source](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license)

**Comment by lsl001006** [comment]
Thanks for your interest in our work. We've added an Apache 2.0 license to the code, and we hope it can be helpful to your work😊
