### ISSUE TITLE
Animation support?

### ISSUE THREAD

**Issue by feiyuhuahuo** [lsl001006/ZONE#2]
Hi, bro, can ZONE  be used for animation images. I found SAM is used so I am thinking whether ZONE is suitable for animation?

**Comment by lsl001006** [comment]
Hi,

Thank you for your interest in our work. Currently, ZONE does not support animation editing. However, we appreciate your suggestion and it would be great if you could explore the possibility of extending ZONE to support animation editing. ZONE is a framework that focuses on solving local image editing problems based on our findings in instruction-guided diffusion models, so it should be promising for animation editing as well. We welcome any discussions on this topic and encourage you to take a step further!

Best regards.
