### ISSUE TITLE
OOD error

### ISSUE THREAD

**Issue by cuixing100876** [lsl001006/ZONE#3]
Hi. Why is there  CUDA out of memory error when you use my own picture, but no error when you use the picture provided in the project? The size of the picture is the same as in the project, set to 512

**Comment by lsl001006** [comment]
Hi,

Thanks for your interest in our work. Could you provide more details about the issue you're encountering? Specifically, we'd like to know about your environment settings, the image you're using, and any error messages you received. Let's try to figure it out together if it still bothers you.

Best regards,

**Comment by cuixing100876** [comment]
Thank you for your answer, this problem is because my picture is in png format, including 4 channels. When I converted it into RGB channels (3 channels), it can run normally. Thanks for your great work.
